<a href="https://colab.research.google.com/github/vijetha0604-afk/Infosys-Springboard-Internship-7.0/blob/main/sample_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving skincare_dataset.xlsx to skincare_dataset (1).xlsx

In [ ]:
df = pd.read_excel("skincare_dataset.xlsx")

In [ ]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55.0,802.0,8661.996792,Non-binary,58.0,7.0,96.0,...,Mumbai,29.0,215.0,29.0,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95.0,736.0,7460.900065,Female,53.0,30.0,37.0,...,NaN,23.0,517.0,30.0,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34.0,8.0,9577.749626,Unknown,1.0,10.0,88.0,...,Mumbai,12.0,971.0,27.0,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,NaN,83.0,7766.836426,Non-binary,23.0,13.0,59.0,...,Kolkata,24.0,937.0,18.0,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26.0,871.0,2686.505152,Non-binary,5.0,3.0,56.0,...,Delhi,5.0,414.0,3.0,92.065161,Fail,3.145580,Air,Route A,923.440632

In [ ]:
df.tail()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
1535,haircare,SKU18,40.338128,22.128674,591.668206,9757.754964,Unknown,10.232899,9.575244,45.617709,...,Kolkata,16.097543,380.479344,16.002634,29.424097,Pending,2.287311,Sea,Route A,603.495967
1536,skincare,SKU90,15.184830,53.485834,333.813638,9600.458348,Non-binary,65.532465,17.384109,93.878658,...,Bangalore,8.297491,599.587586,7.780508,82.821376,Pass,1.191476,NaN,Route B,1039.115728
1537,cosmetics,SKU33,61.637522,62.910887,612.545864,4941.742606,Non-binary,4.016312,17.565338,92.479419,...,Chennai,1.011854,240.752538,24.247444,22.603173,Fail,3.383658,Sea,Route A,417.418582
1538,cosmetics,SKU94,2.881992,NaN,952.077131,7742.511492,Unknown,83.381056,26.585214,71.915260,...,Delhi,13.153875,937.874538,14.707693,62.655548,Pass,1.519385,Rail,Route B,901.130769
1539,skincare,SKU15,37.263058,97.614744,NaN,6149.053643,Non-binary,NaN,8.241768,77.903984,...,Bangalore,14.043555,596.141063,7.101133,96.432599,Pass,2.376588,Sea,Route B,135.929359

In [ ]:
df.shape

(1540, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             1465 non-null   object
 1   SKU                      1449 non-null   object
 2   Price                    1444 non-null   float64
 3   Availability             1446 non-null   float64
 4   Number of products sold  1461 non-null   float64
 5   Revenue generated        1446 non-null   float64
 6   Customer demographics    1465 non-null   object
 7   Stock levels             1466 non-null   float64
 8   Lead times               1473 non-null   float64
 9   Order quantities         1456 non-null   float64
 10  Shipping times           1462 non-null   float64
 11  Shipping carriers        1465 non-null   object
 12  Shipping costs           1474 non-null   float64
 13  Supplier name            1453 non-null   object
 14  Location                 1467 non-null   object
 15  Lead time                1459 non-null   float64
 16  Production volumes       1456 non-null   float64
 17  Manufacturing lead time  1464 non-null   float64
 18  Manufacturing costs      1464 non-null   float64
 19  Inspection results       1460 non-null   object
 20  Defect rates             1457 non-null   float64
 21  Transportation modes     1460 non-null   object
 22  Routes                   1459 non-null   object
 23  Costs                    1466 non-null   float64
dtypes: float64(15), object(9)
memory usage: 288.9+ KB

In [ ]:
df.isnull().sum()

Product type               75
SKU                        91
Price                      96
Availability               94
Number of products sold    79
Revenue generated          94
Customer demographics      75
Stock levels               74
Lead times                 67
Order quantities           84
Shipping times             78
Shipping carriers          75
Shipping costs             66
Supplier name              87
Location                   73
Lead time                  81
Production volumes         84
Manufacturing lead time    76
Manufacturing costs        76
Inspection results         80
Defect rates               83
Transportation modes       80
Routes                     81
Costs                      74
dtype: int64

In [ ]:

numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

In [ ]:
df.isnull().sum()

Product type               75
SKU                        91
Price                       0
Availability                0
Number of products sold     0
Revenue generated           0
Customer demographics      75
Stock levels                0
Lead times                  0
Order quantities            0
Shipping times              0
Shipping carriers          75
Shipping costs              0
Supplier name              87
Location                   73
Lead time                   0
Production volumes          0
Manufacturing lead time     0
Manufacturing costs         0
Inspection results         80
Defect rates                0
Transportation modes       80
Routes                     81
Costs                       0
dtype: int64

In [ ]:

object_columns = df.select_dtypes(include=['object']).columns

for col in object_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(5)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:

text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55.000000,802.0,8661.996792,Non-binary,58.0,7.0,96.0,...,Mumbai,29.0,215.0,29.0,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95.000000,736.0,7460.900065,Female,53.0,30.0,37.0,...,Kolkata,23.0,517.0,30.0,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34.000000,8.0,9577.749626,Unknown,1.0,10.0,88.0,...,Mumbai,12.0,971.0,27.0,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,46.934421,83.0,7766.836426,Non-binary,23.0,13.0,59.0,...,Kolkata,24.0,937.0,18.0,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26.000000,871.0,2686.505152,Non-binary,5.0,3.0,56.0,...,Delhi,5.0,414.0,3.0,92.065161,Fail,3.145580,Air,Route A,923.440632

In [ ]:

text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.title()

In [ ]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,Haircare,Sku0,69.808006,55.000000,802.0,8661.996792,Non-Binary,58.0,7.0,96.0,...,Mumbai,29.0,215.0,29.0,46.279879,Pending,0.226410,Road,Route B,187.752075
1,Skincare,Sku1,14.843523,95.000000,736.0,7460.900065,Female,53.0,30.0,37.0,...,Kolkata,23.0,517.0,30.0,33.616769,Pending,4.854068,Road,Route B,503.065579
2,Haircare,Sku2,11.319683,34.000000,8.0,9577.749626,Unknown,1.0,10.0,88.0,...,Mumbai,12.0,971.0,27.0,30.688019,Pending,4.580593,Air,Route C,141.920282
3,Skincare,Sku3,61.163343,46.934421,83.0,7766.836426,Non-Binary,23.0,13.0,59.0,...,Kolkata,24.0,937.0,18.0,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,Skincare,Sku4,4.805496,26.000000,871.0,2686.505152,Non-Binary,5.0,3.0,56.0,...,Delhi,5.0,414.0,3.0,92.065161,Fail,3.145580,Air,Route A,923.440632

In [ ]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

In [ ]:
df.columns

Index(['Product_type', 'SKU', 'Price', 'Availability',
       'Number_of_products_sold', 'Revenue_generated', 'Customer_demographics',
       'Stock_levels', 'Lead_times', 'Order_quantities', 'Shipping_times',
       'Shipping_carriers', 'Shipping_costs', 'Supplier_name', 'Location',
       'Lead_time', 'Production_volumes', 'Manufacturing_lead_time',
       'Manufacturing_costs', 'Inspection_results', 'Defect_rates',
       'Transportation_modes', 'Routes', 'Costs'],
      dtype='object')

In [ ]:
df.dtypes

Product_type                object
SKU                         object
Price                      float64
Availability               float64
Number_of_products_sold    float64
Revenue_generated          float64
Customer_demographics       object
Stock_levels               float64
Lead_times                 float64
Order_quantities           float64
Shipping_times             float64
Shipping_carriers           object
Shipping_costs             float64
Supplier_name               object
Location                    object
Lead_time                  float64
Production_volumes         float64
Manufacturing_lead_time    float64
Manufacturing_costs        float64
Inspection_results          object
Defect_rates               float64
Transportation_modes        object
Routes                      object
Costs                      float64
dtype: object

In [ ]:
df.describe()

,Price,Availability,Number_of_products_sold,Revenue_generated,Stock_levels,Lead_times,Order_quantities,Shipping_times,Shipping_costs,Lead_time,Production_volumes,Manufacturing_lead_time,Manufacturing_costs,Defect_rates,Costs
count,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000,1535.000000
mean,48.262274,46.969243,462.722081,5761.291470,49.262441,15.809125,48.737113,5.735672,5.669828,17.255885,568.866972,14.939428,47.051277,2.263799,528.671177
std,29.646777,29.594231,289.925358,2660.180713,30.591897,8.741266,26.122741,2.665449,2.575818,8.588554,255.376577,8.691269,28.490783,1.409322,253.229418
min,1.555101,0.887142,7.496523,901.814698,0.000000,0.853299,0.943385,0.851460,0.868602,0.900474,96.132883,0.904858,0.965847,0.017460,93.906076
25%,20.646965,21.661520,208.981863,2868.200650,22.366711,8.257405,25.983394,3.811495,3.835501,10.153832,352.234777,7.116693,24.116678,1.052304,319.680009
50%,48.220725,46.934421,441.662364,5764.024759,49.285915,15.820715,50.387447,5.971653,5.667237,18.247891,569.568264,14.953040,46.592082,2.262277,528.531886
75%,73.232560,71.398458,677.390910,8144.821296,72.104595,23.711505,68.943601,7.962371,7.706890,24.482245,791.049626,22.961941,67.777918,3.424925,751.278585
max,108.444371,115.812891,1083.078792,10866.650881,114.104368,33.119295,103.866994,10.895976,11.097076,32.499698,1089.270729,33.488646,110.733544,5.347179,1104.217060

In [ ]:
df.to_excel("Cleaned_Skincare_Dataset.xlsx", index=False)

In [ ]:
df.isnull().sum()

Product_type               0
SKU                        0
Price                      0
Availability               0
Number_of_products_sold    0
Revenue_generated          0
Customer_demographics      0
Stock_levels               0
Lead_times                 0
Order_quantities           0
Shipping_times             0
Shipping_carriers          0
Shipping_costs             0
Supplier_name              0
Location                   0
Lead_time                  0
Production_volumes         0
Manufacturing_lead_time    0
Manufacturing_costs        0
Inspection_results         0
Defect_rates               0
Transportation_modes       0
Routes                     0
Costs                      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1535, 24)

In [ ]:
df.to_excel("Product_Tracking_Dataset.xlsx", index=False)

In [ ]:
from google.colab import files

files.download("Product_Tracking_Dataset.xlsx")